### ISSUE TITLE
Stalling during Sync.

### ISSUE THREAD

**Issue by cggaurav** [pedro/heroku-mongo-sync#12]
After the 'is syncing log', there is no further logs, and the sync does not start.

http://cl.ly/image/0C0e1r1U0R2S

**Comment by cggaurav** [comment]
Here we go 

Syncing demo (11344)...
 !    Heroku client internal error.
 !    Search for help at: https://help.heroku.com
 !    Or report a bug at: https://github.com/heroku/heroku/issues/new

```
Error:       Query response returned CURSOR_NOT_FOUND. Either an invalid cursor was specified, or the cursor may have timed out on the server. (Mongo::OperationFailure)
Backtrace:   /Users/cggaurav/.rvm/gems/ruby-1.9.3-p194/gems/mongo-1.8.2/lib/mongo/networking.rb:191:in `check_response_flags'
             /Users/cggaurav/.rvm/gems/ruby-1.9.3-p194/gems/mongo-1.8.2/lib/mongo/networking.rb:184:in `receive_response_header'
             /Users/cggaurav/.rvm/gems/ruby-1.9.3-p194/gems/mongo-1.8.2/lib/mongo/networking.rb:151:in `receive'
             /Users/cggaurav/.rvm/gems/ruby-1.9.3-p194/gems/mongo-1.8.2/lib/mongo/networking.rb:117:in `receive_message'
             /Users/cggaurav/.rvm/gems/ruby-1.9.3-p194/gems/mongo-1.8.2/lib/mongo/cursor.rb:529:in `send_get_more'
             /Users/cggaurav/.rvm/gems/ruby-1.9.3-p194/gems/mongo-1.8.2/lib/mongo/cursor.rb:463:in `refresh'
             /Users/cggaurav/.rvm/gems/ruby-1.9.3-p194/gems/mongo-1.8.2/lib/mongo/cursor.rb:124:in `next'
             /Users/cggaurav/.rvm/gems/ruby-1.9.3-p194/gems/mongo-1.8.2/lib/mongo/cursor.rb:285:in `each'
             /Users/cggaurav/.heroku/plugins/heroku-mongo-sync/lib/heroku/command/mongo.rb:34:in `block in transfer'
             /Users/cggaurav/.heroku/plugins/heroku-mongo-sync/lib/heroku/command/mongo.rb:28:in `each'
             /Users/cggaurav/.heroku/plugins/heroku-mongo-sync/lib/heroku/command/mongo.rb:28:in `transfer'
             /Users/cggaurav/.heroku/plugins/heroku-mongo-sync/lib/heroku/command/mongo.rb:15:in `push'
             /Users/cggaurav/.rvm/gems/ruby-1.9.3-p194/gems/heroku-2.31.2/lib/heroku/command.rb:191:in `run'
             /Users/cggaurav/.rvm/gems/ruby-1.9.3-p194/gems/heroku-2.31.2/lib/heroku/cli.rb:28:in `start'
             /Users/cggaurav/.rvm/gems/ruby-1.9.3-p194/gems/heroku-2.31.2/bin/heroku:16:in `<top (required)>'
             /Users/cggaurav/.rvm/gems/ruby-1.9.3-p194/bin/heroku:19:in `load'
             /Users/cggaurav/.rvm/gems/ruby-1.9.3-p194/bin/heroku:19:in `<main>'
             /Users/cggaurav/.rvm/gems/ruby-1.9.3-p194/bin/ruby_noexec_wrapper:14:in `eval'
             /Users/cggaurav/.rvm/gems/ruby-1.9.3-p194/bin/ruby_noexec_wrapper:14:in `<main>'

Command:     heroku mongo:push
Plugins:     heroku-mongo-sync
             heroku-sendgrid-stats

Version:     heroku-gem/2.31.2 (x86_64-darwin11.4.0) ruby/1.9.3
```

**Comment by marcofognog** [comment]
That seems a connection problem to me. Are you still having this issue?

**Comment by pedro** [comment]
Hey there, 

So sorry for dropping the ball here. In case you still have any interest please refer to Marco's fork, he's maintaining this plugin now:
https://github.com/marcofognog/heroku-mongo-sync

Thanks
